# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.description }}, and so on.
#
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: JSON Lines
description: >-
  This page describes the JSON Lines text format, also called newline-delimited JSON.
  JSON Lines is a convenient format for storing structured data that may be processed
  one record at a time. It works well with unix-style text processing tools and shell
  pipelines. It's a great format for log files. It's also a flexible format for passing
  messages between cooperating processes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsonlines.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
  
# Disable warning related to https://sass-lang.com/d/slash-div
sass:
  quiet_deps: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
